version: 2.1

orbs:
  python: circleci/python@1.1.0
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  unit:
    docker:
      - image: dataders/pyodbc:1.4
    steps:
      - checkout
      - run: tox -- -v test/unit
  integration-sqlserver: &sqlserver
    docker:
      - image: dataders/pyodbc:1.4
      - image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          ACCEPT_EULA: 'yes'
          MSSQL_SA_PASSWORD: 5atyaNadella
          MSSQL_IP_ADDRESS: 0.0.0.0
    executor: python/default
    steps:
      - run: &install-git
          name: "TEMP: install Git"
          command: |
            apt-get install -y git
      - run:
          name: "TEMP: upgrade dbt"  # hot fix: dbt is installed in the pyodbc docker image, it should be removed there
          command: |
            pip install --upgrade dbt
      - checkout
      - run:
          name: wait for SQL Server container to set up
          command: sleep 30
      - run:
          name: test connection via SQL CMD
          command: sqlcmd -S 'localhost,1433' -U sa -P 5atyaNadella -Q 'create database blog'
      - run:
          name: Test adapter on SQL Server against dbt-adapter-tests
          command: tox -- -v test/integration/sqlserver.dbtspec
  connection-sqlserver:
    <<: *sqlserver
    steps:
      - run: *install-git
      - checkout
      - run: &install-dbt-sqlserver
          name: "install dbt-sqlserver"
          command: python setup.py install
      - run:
          name: wait for SQL Server container to set up
          command: sleep 30
      - run: &prep=connect
          name: prep for connecting
          command: |
            mkdir -p ~/.dbt
            cp test/integration/sample.profiles.yml ~/.dbt/profiles.yml
      - run:
          name: cnxn -- SQL Server - local sql cred
          command: |
            cd test/integration
            dbt compile --target sqlserver_local_userpass
      - run:
          name: cnxn -- SQL Server - local sql cred encrypt
          command: |
            cd test/integration
            dbt compile --target sqlserver_local_encrypt

  integration-azuresql:
    docker:
      - image: dataders/pyodbc:1.4
    executor: python/default
    steps:
      - run: *install-git
      - checkout
      - run: *install-dbt-sqlserver
      - run:
          name: wake up serverless db
          command: |
            cd test/integration
            dbt debug --target azuresql_sqlcred
      - run:
          name: Test adapter on Azure SQL against dbt-adapter-tests
          command: tox -- -v test/integration/azuresql.dbtspec
  connection-azuresql:
    docker:
      - image: dataders/pyodbc:1.4
    executor: python/default
    steps:
      - run: *install-git
      - checkout
      - run: *install-dbt-sqlserver
      - run:
          name: install gnupg
          command: apt-get install gnupg -y
      - azure-cli/install
      - run: *prep=connect
      - run:
          name: cnxn -- Azure SQL - SQL cred
          command: |
            cd test/integration
            dbt compile --target azuresql_sqlcred
      - run:
          name: cnxn -- Azure SQL - SQL CRED user+pass
          command: |
            cd test/integration
            dbt compile --target azuresql_azcli
      - azure-cli/login-with-user:
          azure-username: DBT_AZURE_USERNAME
          azure-password: DBT_AZURE_PASSWORD
          alternate-tenant: true
          azure-tenant: DBT_AZURE_TENANT
      - run:
          name: cnxn -- Azure SQL - AZ CLI User
          command: |
            cd test/integration
            dbt compile --target azuresql_azcli
      - azure-cli/login-with-service-principal:
          azure-sp: DBT_AZURE_SP_NAME
          azure-sp-password: DBT_AZURE_SP_SECRET
          azure-sp-tenant: DBT_AZURE_TENANT
      - run:
          name: cnxn -- Azure SQL - AZ CLI ServicePrincipal
          command: tox --workdir test/integration -e dbt -- compile --target azuresql_azcli

workflows:
  main:
    jobs:
      - unit
      - connection-azuresql:
          context:
            - DBT_SYNAPSE_PROFILE
      - connection-sqlserver:
          context:
            - DBT_SYNAPSE_PROFILE
      - integration-sqlserver
      - integration-azuresql:
          context:
            - DBT_SYNAPSE_PROFILE
