version: 2.1

orbs:
  python: circleci/python@2.0.3
  azure-cli: circleci/azure-cli@1.2.2

jobs:
  release-new-version:
    docker:
      - image: ghcr.io/dbt-msft/dbt-sqlserver:latest
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: dev_requirements.txt
      - run:
          name: "install dbt-sqlserver"
          command: |
            pip install .
      - run:
          name: verify git tag vs. version
          command: python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_DBT_SQLSERVER" >> ~/.pypirc
      - run:
          name: build and publish package
          command: |
            python setup.py sdist bdist_wheel
            twine upload dist/*

workflows:
  main:
    jobs:
      - release-new-version:
          context:
            - DBT_SYNAPSE_PROFILE
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
