---
name: Integration tests on SQL Server
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - v*
  pull_request:
    branches:
      - master
      - v*

jobs:
  integration-tests-sql-server:
    name: Integration tests on SQL Server
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]
        profile: ["ci_sql_server", "ci_sql_server_encrypt"]
        msodbc_version: ["17", "18"]
        sqlserver_version: ["2017", "2019", "2022"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ matrix.python_version }}-msodbc${{ matrix.msodbc_version }}
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:${{ matrix.sqlserver_version }}-latest
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 5atyaNadella
    steps:
      - uses: actions/checkout@v3

      - name: Configure test users
        run: sqlcmd -b -I -i devops/create_sql_users.sql
        env:
          DBT_TEST_USER_1: DBT_TEST_USER_1
          DBT_TEST_USER_2: DBT_TEST_USER_2
          DBT_TEST_USER_3: DBT_TEST_USER_3
          SQLCMDUSER: SA
          SQLCMDPASSWORD: 5atyaNadella
          SQLCMDSERVER: sqlserver
          SQLCMDDBNAME: msdb

      - name: Install dependencies
        run: pip install -r dev_requirements.txt

      - name: Run functional tests
        run: pytest tests/functional --profile "${{ matrix.profile }}"
