---
name: Integration tests on SQL Server
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - v*
  pull_request:
    branches:
      - master
      - v*

jobs:
  integration-tests-sql-server:
    name: Integration tests on SQL Server
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]
        profile: ["ci_sql_server", "ci_sql_server_encrypt"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ matrix.python_version }}
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 5atyaNadella
    steps:
      - uses: actions/checkout@v3

      - name: Configure test users
        run: opt/mssql-tools/bin/sqlcmd -b -I -i devops/create_sql_users.sql
        env:
          DBT_TEST_USER_1: DBT_TEST_USER_1
          DBT_TEST_USER_2: DBT_TEST_USER_2
          DBT_TEST_USER_3: DBT_TEST_USER_3
          SQLCMDUSER: SA
          SQLCMDPASSWORD: 5atyaNadella
          SQLCMDSERVER: localhost
          SQLCMDDBNAME: msdb

      - name: Install dependencies
        run: pip install -e . && pip install -r dev_requirements.txt

      - name: Run functional tests
        run: |
          RAW_TOXENV="py${{ matrix.python_version }}"
          TOXENV=$(echo $RAW_TOXENV | sed 's/\.//')
          tox -e "$TOXENV" -- tests/functional --profile "${{ matrix.profile }}"
