---
name: Integration tests on Azure
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - v*
  pull_request_target:
    types: [labeled]

jobs:
  integration-tests-azure:
    name: Integration tests on Azure
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.ref_name == 'master'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]
        profile: ["ci_azure_cli", "ci_azure_auto", "ci_azure_environment", "ci_azure_basic"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -e . && pip install -r dev_requirements.txt

      - name: Wake up server
        env:
          DBT_AZURESQL_SERVER: ${{ secrets.DBT_AZURESQL_SERVER }}
          DBT_AZURESQL_DB: ${{ secrets.DBT_AZURESQL_DB }}
          DBT_AZURESQL_UID: ${{ secrets.DBT_AZURESQL_UID }}
          DBT_AZURESQL_PWD: ${{ secrets.DBT_AZURESQL_PWD }}
        run: python devops/wakeup_azure.py

      - name: Configure test users
        run: opt/mssql-tools/bin/sqlcmd -b -I -i devops/create_sql_users.sql
        env:
          DBT_TEST_USER_1: DBT_TEST_USER_1
          DBT_TEST_USER_2: DBT_TEST_USER_2
          DBT_TEST_USER_3: DBT_TEST_USER_3
          SQLCMDUSER: ${{ secrets.DBT_AZURESQL_UID }}
          SQLCMDPASSWORD: ${{ secrets.DBT_AZURESQL_PWD }}
          SQLCMDSERVER: ${{ secrets.DBT_AZURESQL_SERVER }}
          SQLCMDDBNAME: ${{ secrets.DBT_AZURESQL_DB }}

      - name: Run functional tests
        env:
          DBT_AZURESQL_SERVER: ${{ secrets.DBT_AZURESQL_SERVER }}
          DBT_AZURESQL_DB: ${{ secrets.DBT_AZURESQL_DB }}
          DBT_AZURESQL_UID: ${{ secrets.DBT_AZURESQL_UID }}
          DBT_AZURESQL_PWD: ${{ secrets.DBT_AZURESQL_PWD }}
          DBT_AZURE_USERNAME: ${{ secrets.DBT_AZURE_USERNAME }}
          DBT_AZURE_PASSWORD: ${{ secrets.DBT_AZURE_PASSWORD }}
          AZURE_CLIENT_ID: ${{ secrets.DBT_AZURE_SP_NAME }}
          AZURE_CLIENT_SECRET: ${{ secrets.DBT_AZURE_SP_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.DBT_AZURE_TENANT }}
          DBT_TEST_USER_1: DBT_TEST_USER_1
          DBT_TEST_USER_2: DBT_TEST_USER_2
          DBT_TEST_USER_3: DBT_TEST_USER_3
        run: |
          RAW_TOXENV="py${{ matrix.python_version }}-azure"
          TOXENV=$(echo $RAW_TOXENV | sed 's/\.//')
          tox -e "$TOXENV" -- tests/functional --profile "${{ matrix.profile }}"
