---
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/${{ github.repository }}:${{ matrix.python_version }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r dev_requirements.txt

      - name: Run unit tests
        run: |
          RAW_TOXENV="py${{ matrix.python_version }}"
          TOXENV=$(echo $RAW_TOXENV | sed 's/\.//')
          tox -e "$TOXENV" -- tests/unit
